title: Dai's blog
description: > # this means to ignore newlines until "baseurl:"
  Phuc Dai Huynh's personal blog. I use this blog for stories around my study, researching, and working experience.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Phuc Dai Huynh # add your name
author-img: avatar.jpg # add your photo
about-author: I am a game developer, software engineer, and a data scientist. I am pursuing a Master's degree in Data Science at University of South Australia
social-twitter: HuynhPhucDai
social-facebook: huynhphucdai
social-github: daihuynh # add your Github handle
social-linkedin: dai-huynh-90615057
social-email: huynhphucdai@gmail.com

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
